export interface Track {
  idAlbum: string;
  idArtist: string;
  idIMVDB?: string | null;
  idLyric: string;
  idTrack: string;
  intCD?: string | null;
  intDuration: string;
  intLoved: string;
  intMusicVidComments?: string | null;
  intMusicVidDislikes?: string | null;
  intMusicVidFavorites?: string | null;
  intMusicVidLikes?: string | null;
  intMusicVidViews?: string | null;
  intScore?: string | null;
  intScoreVotes?: string | null;
  intTotalListeners?: string | null;
  intTotalPlays?: string | null;
  intTrackNumber: string;
  strAlbum: string;
  strArtist: string;
  strArtistAlternate?: string | null;
  strDescriptionEN?: string | null;
  strGenre: string;
  strLocked: string;
  strMood?: string | null;
  strMusicBrainzAlbumID: string;
  strMusicBrainzArtistID: string;
  strMusicBrainzID: string;
  strMusicVid?: string | null;
  strMusicVidCompany?: string | null;
  strMusicVidDirector?: string | null;
  strMusicVidScreen1?: string | null;
  strMusicVidScreen2?: string | null;
  strMusicVidScreen3?: string | null;
  strStyle?: string | null;
  strTheme?: string | null;
  strTrack: string;
  strTrack3DCase?: string | null;
  strTrackLyrics?: string | null;
  strTrackThumb?: string | null;
}

export interface Album {
  idAlbum: string;
  idArtist: string;
  idLabel: string;
  strAlbum: string;
  strAlbumStripped: string;
  strArtist: string;
  strArtistStripped: string;
  intYearReleased: string;
  strStyle: string;
  strGenre: string;
  strLabel: string;
  strReleaseFormat: string;
  intSales: string;
  strAlbumThumb: string | null;
  strAlbumThumbHQ: string | null;
  strAlbumThumbBack: string | null;
  strAlbumCDart: string | null;
  strAlbumSpine: string | null;
  strAlbum3DCase: string | null;
  strAlbum3DFlat: string | null;
  strAlbum3DFace: string | null;
  strAlbum3DThumb: string | null;
  strDescriptionEN: string | null;
  strDescriptionDE: string | null;
  strDescriptionFR: string | null;
  strDescriptionCN: string | null;
  strDescriptionIT: string | null;
  strDescriptionJP: string | null;
  strDescriptionRU: string | null;
  strDescriptionES: string | null;
  strDescriptionPT: string | null;
  strDescriptionSE: string | null;
  strDescriptionNL: string | null;
  strDescriptionHU: string | null;
  strDescriptionNO: string | null;
  strDescriptionIL: string | null;
  strDescriptionPL: string | null;
  intLoved: string | null;
  intScore: string | null;
  intScoreVotes: string | null;
  strReview: string;
  strMood: string | null;
  strTheme: string | null;
  strSpeed: string | null;
  strLocation: string | null;
  strMusicBrainzID: string;
  strMusicBrainzArtistID: string;
  strAllMusicID: string | null;
  strBBCReviewID: string | null;
  strRateYourMusicID: string | null;
  strDiscogsID: string | null;
  strWikidataID: string | null;
  strWikipediaID: string | null;
  strGeniusID: string | null;
  strLyricWikiID: string | null;
  strMusicMozID: string | null;
  strItunesID: string | null;
  strAmazonID: string | null;
  strLocked: string;
}
